- hosts: servera
  gather_facts: no
  tasks:
          - debug:
                  msg: "{{ 'redhat'|hash('sha1')}}"
                  #使用sha1加密字符串redhat
          - debug:
                  msg: "{{ 'redhat'|password_hash('sha512')}}"
                  #使用哈希512加密字符串redhat
          - debug:
                  msg: "{{ 'redhat'|b64encode }}"
                  #使用base64加密字符串redhat
          - debug:
                  msg: "{{ 'cmVkaGF0'|b64decode }}"
                  #使用base64进行解密
