- hosts: servera
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ 'hello, redhat;hello,redhat' | replace('redhat','huawei') }}"
        #将redhat替换为huawei，replace('查找内容','替换内容')
        #不支持正则
    - debug:
        msg: "{{ 'hello,redhat;hello,redhat'|regex_replace('redhat$','huawei') }}"
        #使用正则表达式进行查找替换
    - debug:
            msg: "{{ lookup('file','/etc/hosts')|regex_search('[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}')}}"
       #使用regex_search查找字符串；返回第一个找到的字符串或者是子字符串

    - debug:
            msg: "{{ lookup('file','/etc/hosts')|regex_findall('[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}')}}"
       #使用regex_findall查找字符串；并返回所有结果

